"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tsXml_1 = require("./tsXml");
// let divElement = CreateDivEmlement("Welcome to TypeScript Demo!");
// console.log(divElement);
// console.log(greet("TypeScript Learner"));
// console.log(doingTask("Learning TypeScript"));
// console.log(add(1,5))
// console.log(address);
// console.log(hobbies);
// console.log(complexObject);
// let pruthvi = new employee(3,"Pruthvi",70000,"Pruthvi@123","pruthvi@123","Department:Finance","Locations:Banglore");
// pruthvi.swipe();
// console.log(pruthvi);
var interfaceDemo_1 = require("./interfaceDemo");
interfaceDemo_1.crow.fly();
(0, tsXml_1.CreateDivEmlement)("Crow is flying");
interfaceDemo_1.boeing.fly();
(0, tsXml_1.CreateDivEmlement)("Boeing is flying");
interfaceDemo_1.superman.fly();
(0, tsXml_1.CreateDivEmlement)("Superman is flying");
